### ISSUE TITLE
Cannot compile the project 

### ISSUE THREAD

**Issue by gspasov** [mbrix/lib_hd#1]
I cloned the project localy, runned ```rebar get-deps``` and then ```rebar compile euint``` but I get the following error

```/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
ERROR: sh(cc c_src/libsecp256k1_nif.o  -lstdc++ -shared  -L"/home/georgi/.asdf/installs/erlang/20.0/lib/erlang/lib/erl_interface-3.10/lib" -lerl_interface -lei c_src/secp256k1/.libs/libsecp256k1.a -lgmp -o priv/libsecp256k1_nif.so)
failed with return code 1 and the following output:
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /home/georgi/ElixirTut/Erlang-libs/lib_hd/deps/libsecp256k1: rebar_abort
```

Btw are you familiar that the crypto module has the crypto:generate_key(ecdh. secp256k1, Key) function? Maybe it could be interchanged with the one you are currently using, but because I'm not completely sure how you use the secp256k1 library I cannot do it.

**Comment by mbrix** [comment]
It's probably because I need to update libsecp256k1 bindings. I use that
module because it's the actual library used in Bitcoin. It's preferable to
the builtin.

I'm on business for a few days so don't have time to update this binding
right now. I will look into it later this week.

**Comment by gspasov** [comment]
Soo? 23 days later, any progress? :)

**Comment by mbrix** [comment]
Not really, sorry, I just have other projects. Pull request welcome.

**Comment by gspasov** [comment]
Well, can't really do that, because I'm using your code as a reference on how I can implement the extended child key derivations on Elixir. I can understand most of the code, but still I'm missing some pieces, because I can't derive  the child keys. Even with path " m/0' ".

This is where you use the libsecp256k1 lib
```
{ok, NewKey} = libsecp256k1:ec_privkey_tweak_add(PrivKey, K2#bip32_priv_key.key)
```
I don't use any library, i do it by theory using the [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key)

I'm wondering what depth would the first hardned child have. As far as it makes logic to me it should be 1. But with 1, even the first part of the extended key is not equal.

Correct: xprv9uHRZZhk6KAJC1avXpDAp4MDc3sQKNxDiPvvkX8Br5ngLNv1TxvUxt4cV1rGL5hj6KCesnDYUhd7oWgT11eZG7XnxHrnYeSvkzY7d2bhkJ7

Mine: xprv9ufGfNderzpCsMKKJnMEPj56CW9BjoExkrfCxrEtnaZDm6CUJiHWrQCXswX7oqvT6WQjdqRrsgZogQ6oAnfgXrtUHXdBT6aKXsSYtuzEvWV

PS. My Master Extended priv/pub key derivation is working properly

**Comment by mbrix** [comment]
It's not a lib hd issue, it's in the supporting lib256kp1 nif. If you are
doing this commercially consider sponsoring development if it's important,
because it's not really on my radar right this second.

**Comment by gspasov** [comment]
I found where was my mistake. I was missing some library. Everything was fixed after I ran this command: ```sudo apt-get install libgmp3-dev```

Sorry for the hassle
